### ISSUE TITLE
Successfully compiles on Mac M1 macOS Ventura 13.4

### ISSUE THREAD

**Issue by davidmrnustik** [profitviews/heisenberg#10]
Hello,
This is not an issue, just a report that I've successfully compiled and run **algo** app on macOS Ventura 13.4, which I wasn't able to do it on macOS Monterey. My macOS Ventura has **Command Line Tools for Xcode 14.3.1** installed.

I've also updated **cmake**, **boost** and **openssl** versions in `conanfile.txt`

```
[build_requires]
cmake/3.25.2

[requires]
boost/1.80.0
fmt/8.1.1
openssl/1.1.1t
rapidjson/cci.20211112

[generators]
cmake_find_package
virtualenv
```

In the step of installing conan in virtual env, I installed a specific version of conan (the last 1.x version before v2.0):
```
pip install conan==1.59
```

My conan `default` profile:
```
[settings]
os=Macos
os_build=Macos
arch=armv8
arch_build=armv8
compiler=apple-clang
compiler.version=14
compiler.libcxx=libc++
build_type=Release
[options]
[build_requires]
[env]
```

**Comment by rthickling** [comment]
Great - thank you for this.

**Comment by Twon** [comment]
Thanks for the useful feedback!  I'll close this issue now thanks, please reopen if you have more to add.
